In [2]:
import pandas as pd

In [3]:
df_consumption = pd.read_excel("energy_sources.xlsx", sheet_name="energy consumption by sources", engine='openpyxl')
# df_2 = pd.read_excel("online_retail_II.xlsx", sheet_name="Year 2010-2011", engine='openpyxl')

In [6]:
df_consumption

,Entity,Code,Year,Oil Consumption - EJ,Gas Consumption - EJ,Coal Consumption - EJ,Solar Consumption - EJ,Hydro Consumption - EJ,Nuclear Consumption - EJ,Wind Consumption - EJ,Geo Biomass Other - EJ,Biofuels (TWh)
0,Africa,NaN,1965,325.900637,9.543762,323.496397,0.0,38.626795,0.0,0.0,0.0,0.0
1,Africa,NaN,1966,356.709630,10.669925,323.122452,0.0,43.083379,0.0,0.0,0.0,0.0
2,Africa,NaN,1967,353.833321,10.545678,330.291849,0.0,44.974026,0.0,0.0,0.0,0.0
3,Africa,NaN,1968,373.394345,10.688978,343.513186,0.0,52.606544,0.0,0.0,0.0,0.0
4,Africa,NaN,1969,378.536268,12.492010,346.643199,0.0,61.391409,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6555,Zimbabwe,ZWE,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
6556,Zimbabwe,ZWE,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
6557,Zimbabwe,ZWE,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
6558,Zimbabwe,ZWE,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
6559,Zimbabwe,ZWE,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [9]:
df_consumption.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6560 entries, 0 to 6559
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Entity                    6560 non-null   object
 1   Code                      5515 non-null   object
 2   Year                      6560 non-null   int64
 3   Oil Consumption - EJ      5184 non-null   float64
 4   Gas Consumption - EJ      5170 non-null   float64
 5   Coal Consumption - EJ     5170 non-null   float64
 6   Solar Consumption - EJ    5170 non-null   float64
 7   Hydro Consumption - EJ    5170 non-null   float64
 8   Nuclear Consumption - EJ  5170 non-null   float64
 9   Wind Consumption - EJ     5170 non-null   float64
 10  Geo Biomass Other - EJ    5170 non-null   float64
 11  Biofuels (TWh)            5660 non-null   float64
dtypes: float64(9), int64(1), object(2)
memory usage: 615.1+ KB

In [10]:
df_consumption.describe().T

,count,mean,std,min,25%,50%,75%,max
Year,6560.0,1993.279878,16.817524,1900.0,1980.000000,1995.000000,2007.000000,2019.000000
Oil Consumption - EJ,5184.0,1238.016345,4534.636836,0.0,67.638718,154.226531,512.243680,53619.924663
Gas Consumption - EJ,5170.0,665.597771,2606.562650,0.0,7.863221,51.688061,259.311156,39292.467575
Coal Consumption - EJ,5170.0,894.623197,3800.362116,0.0,2.370775,31.787536,200.209171,44993.467099
Solar Consumption - EJ,5170.0,4.288249,48.548311,0.0,0.000000,0.000000,0.009598,1792.996379
Hydro Consumption - EJ,5170.0,202.856806,770.151902,0.0,2.260097,16.853315,82.416361,10455.126737
Nuclear Consumption - EJ,5170.0,145.148331,645.536422,0.0,0.000000,0.000000,22.576011,7493.281090
Wind Consumption - EJ,5170.0,14.108595,120.145186,0.0,0.000000,0.000000,0.109423,3540.051401
Geo Biomass Other - EJ,5170.0,15.727659,78.581685,0.0,0.000000,0.121667,3.671460,1614.026957
Biofuels (TWh),5660.0,5.795995,48.789425,0.0,0.000000,0.000000,0.000000,1101.949000

In [18]:
df_consumption['Biofuels - EJ'] = df_consumption['Biofuels (TWh)'].apply(lambda x: (x*3.6)/1000)
df_consumption = df_consumption.drop(['Biofuels (TWh)'], axis=1)

In [19]:
df_consumption.describe().T

,count,mean,std,min,25%,50%,75%,max
Year,6560.0,1993.279878,16.817524,1900.0,1980.000000,1995.000000,2007.000000,2019.000000
Oil Consumption - EJ,5184.0,1238.016345,4534.636836,0.0,67.638718,154.226531,512.243680,53619.924663
Gas Consumption - EJ,5170.0,665.597771,2606.562650,0.0,7.863221,51.688061,259.311156,39292.467575
Coal Consumption - EJ,5170.0,894.623197,3800.362116,0.0,2.370775,31.787536,200.209171,44993.467099
Solar Consumption - EJ,5170.0,4.288249,48.548311,0.0,0.000000,0.000000,0.009598,1792.996379
Hydro Consumption - EJ,5170.0,202.856806,770.151902,0.0,2.260097,16.853315,82.416361,10455.126737
Nuclear Consumption - EJ,5170.0,145.148331,645.536422,0.0,0.000000,0.000000,22.576011,7493.281090
Wind Consumption - EJ,5170.0,14.108595,120.145186,0.0,0.000000,0.000000,0.109423,3540.051401
Geo Biomass Other - EJ,5170.0,15.727659,78.581685,0.0,0.000000,0.121667,3.671460,1614.026957
Biofuels - EJ,5660.0,0.020866,0.175642,0.0,0.000000,0.000000,0.000000,3.967016